experiment: 'context_davis'

### Dataset paths
dataset_path: 'actual_dataset'    # sample_dataset, actual_dataset
dataset_list: 'davis'             # davis, videvo, both (add sample_ for sample dataset)

### Save paths
model_dir: 'saved_models'
model_name: 'context2_davis'

### Architecture
Encoder:
  context: 2
  activation: 'relu'
  sim_kernel_size: 3
  mix_kernel_size: 3

### Dataloader
Setup:
  epochs: 60
  scheduler: 'CALR'
  # scheduler_params:
    # patience:
  optimizer: 'Adam'
  optimizer_params:
    lr: 0.001
    # betas: (0.9, 0.99)
    weight_decay: 0.001
    eps: 0.00003

  loss: 'MSE'

  model_mode: 'context'       # cic/ context/ attention
  freeze_cic: True

  context: 2
  batch_size: 32
  dataloader_params:
    shuffle: True
    num_workers: 4
    pin_memory: True

  device: 'cuda'
  wandb_log: True